### PR TITLE
Fix timecode

### PR DESCRIPTION
**Pull request by Dananji**
Change peaks.js timecode format, so that waveform shows timecode as it is used in Avalon (`hh:mm:ss.sss`). I found no exposed API methods to change the timecode format. 

So the solution included in this PR is;
Instead of pulling `peaks.js` from npm registry, use the patched `peaks.js` code locally (similar to 
how `mediaelement.js` is used in Avalon).

### CODE REVIEW

**Comment by cjcolvar** [comment]
Can you please show me the lines of the patch in peaks.js?

**Comment by Dananji** [comment]
> Can you please show me the lines of the patch in peaks.js?

Yes, it is here https://github.com/avalonmediasystem/react-structural-metadata-editor/blob/9c5b963045af200918b8deb298a6e97a5beb7dbe/vendor/javascript/peaks.js#L20711

Previously it was like this
https://github.com/bbc/peaks.js/blob/0ed5ea88f93057e78fd3d5590c00e31d17dc09ed/src/utils.js#L42

**Comment by cjcolvar** [comment]
I kind of hate to bring in a forked peaks.js just for this change since I think it brings a lot of technical debt.  Since the peaks.js maintainers have been really responsive before, how about making a PR which adds an optional parameter for precision places (defaulting to 2 since that would be backwards compatible)?  We would have to figure out how to pass that value in though so it might mean touching more places in the code in order to surface that configuration point in `peaks.options`.  Does that seem feasible?  It might take more work, but it could be a good contribution to the library and keep us from incurring tech debt.

**Comment by Dananji** [comment]
Yes, I like that suggestion. I will make a PR to peaks.js.

**Pull request closed without merging**
