### PR TITLE
Upgrade Peaks.js to latest stable version: 0.26.0

### PR DESCRIPTION
**Pull request by Dananji**
This needs to be tested on a Google Chrome browser, for me it works on both Safari and Firefox.

To test it out;
1. Pull the changes in the branch into local machine
2. `yarn install`
3. `yarn start`
4. Connect to IU VPN
5. Go to http://localhost:3001
6. Check whether the loading spinner stops and the streaming works
7. Check editing timespans and headings work

### CODE REVIEW

**Comment by cjcolvar** [comment]
@Dananji I can't test this because the demo content went offline when I migrated the test servers.  Is it possible to switch this to use bundled content or does it need to run against a live Avalon instance?  If it does then maybe we could set it up to use a docker-compose setup?  Sorry to hold up this PR.

**Comment by Dananji** [comment]
@cjcolvar I changed the demo to run against an item in MCO in `master`, when I created the GitHub demo page for this repo. I rebased this branch now, so the demo content should work now.
But I'd rather use demo content from `maple` like in `iiif-react-media-player`.
Question: what is "bundled content" you mentioned?

**Comment by cjcolvar** [comment]
By "demo content" I was meaning putting everything needed for testing/debugging/demoing in this repository so it doesn't depend on anything external.

`maple` is gone as well (or will be real soon) so we'll need to find a place for that content as well.

I'll test this out in chrome soon.

**Comment by cjcolvar** [comment]
I tested in ungoogled-chromium 96.0.4664.110-1 on linux and it failed to finish loading.  The error I saw on the console was failed to load a blob.  FWIW the peaks.js demo page worked fine (although it might be running a newer version of peaks.js since I see that 0.27.0 was released in November).

**Comment by Dananji** [comment]
Thanks Chris! I'll upgrade to the latest version and try again. If it doesn't work, then let's downgrade to the newest version that works properly.

**Review by cjcolvar — APPROVED** [review]
This looks like it was tricky work!  I don't really understand the nuances of the changes but it works for me on both firefox and chromium. :sparkles:

**Comment by Dananji** [comment]
Thank you for the review @cjcolvar !

As far as I understood, this version of `peaks.js` carries changes to a function which handles the source(s) of the `mediaElement` component passed to it. On our end we are using `hls.js` , which makes changes to the source(s) of the media element when fetching the stream media.

And it seems the `hls.js`'s functionality was impeded by the changes made in the `peaks.js` library. And waiting for `peaks.js` to finish setting up things, before `hls.js` handles the streaming fixed the issue.

**Pull request merged**
